INSERT INTO CITY ( "NAME", AREA, POPULATION, METRO, REGION ) VALUES ('서울',605,974,1,'서울');
INSERT INTO CITY ( "NAME", AREA, POPULATION, METRO, REGION ) VALUES ('부산',765,342,1,'부산');
INSERT INTO CITY ( "NAME", AREA, POPULATION, METRO, REGION ) VALUES ('오산',42,21,0,'경기');
INSERT INTO CITY ( "NAME", AREA, POPULATION, METRO, REGION ) VALUES ('청주',940,83,0,'충청');
INSERT INTO CITY ( "NAME", AREA, POPULATION, METRO, REGION ) VALUES ('전주',205,65,0,'전라');
INSERT INTO CITY ( "NAME", AREA, POPULATION, METRO, REGION ) VALUES ('순천',910,27,0,'전라');
INSERT INTO CITY ( "NAME", AREA, POPULATION, METRO, REGION ) VALUES ('춘천',1116,27,0,'강원');
INSERT INTO CITY ( "NAME", AREA, POPULATION, METRO, REGION ) VALUES ('홍천',1819,7,0,'강원');

COMMIT;